CREATE TABLE TB_MESSAGE(
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 ACCOUNT STRING,
 CC STRING, 
 BCC STRING,
 SUBJECT STRING,
 MESSAGE STRING
);

CREATE TABLE TB_INCOME_MESSAGE_REQUEST(
 ID INTEGER PRIMARY KEY AUTOINCREMENT, 
 DATE_TIME INTEGER, 
 SEQ_NUMBER INTEGER
);
	